### ISSUE TITLE
Add the ability to change the schema of database context

### ISSUE THREAD

**Issue by alaincroisetiere** [RockSolidKnowledge/RSK.IdentityServer4.AuditEventSink#2]
Would it be possible to add the ability to change the schema of the table AuditEntries in AuditDatabaseContext ?

**Comment by alaincroisetiere** [comment]
✋

**Comment by scottbrady91** [comment]
Hi! You can extend the schema by overriding the `OnModelCreating` method on `AuditDatabaseContext`; however, since AdminUI relies upon our EF implementation, we cannot change the DbContext in our Rsk.Audit.Ef library or offer extensibility points out of the box.

**Comment by scottbrady91** [comment]
Was there anything specific you were trying to achieve?

**Comment by alaincroisetiere** [comment]
Yes, a solution more out of the box like [IdentityServer](https://github.com/DuendeSoftware/IdentityServer/blob/e8e855c41b3d08206fa8668f1900685565dc1d8b/src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs#L30) to not override DbContext and break Rsk.Audit.Ef.

**Comment by scottbrady91** [comment]
Ah, okay, it was the default schema. Unfortunately, we cannot offer that since the EF implementation is tightly coupled to AdminUI.

If you need to change the default schema and don't use AdminUI, I recommend implementing your own DbContext and audit stores.
